module: default
runtime: custom
vm: true

api_version: 1
threadsafe: true

resources:
  cpu: .5
  memory_gb: 1.3

#Manual Scaling
# manual_scaling:
#  instances: 1

#Auto Scaling
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.75

handlers:
- url: .*
  script: main.app

